# ╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╱   ╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╱╱╱
# ┃╭━╮┃╱╱╱╱╱╱╱╱╱╱╱╱   ┃╭━━╯╱╱╱╱╱╱╱╱╱╱╱╱╱╱
# ┃┃╱╰╯╭╮╭╮╭━━╮╭━━╮   ┃╰━━╮╭━━╮╭━━╮╭╮╭╮╭╮
# ┃┃╭━╮┃┃┃┃┃╭╮┃┃╭╮┃   ┃╭━━╯┃┃━┫┃╭╮┃┣┫╰╋╋╯
# ┃╰┻━┃┃╰╯┃┃╰╯┃┃╭╮┃   ┃┃╱╱╱┃┃━┫┃┃┃┃┃┃╭╋╋╮
# ╰━━━╯╰━━╯╰━╮┃╰╯╰╯   ╰╯╱╱╱╰━━╯╰╯╰╯╰╯╰╯╰╯
# ╱╱╱╱╱╱╱╱╱╭━╯┃╱╱╱╱   ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱
# ╱╱╱╱╱╱╱╱╱╰━━╯╱╱╱╱   ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱


# ╭━━━╮╭╮╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱
# ┃╭━╮┃┃┃╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱
# ┃┃╱╰╯┃┃╱╭━━╮╭━╯┃╭╮╭━━╮╭━╯┃╭━━╮╭━╮
# ┃┃╭━╮┃┃╱┃╭╮┃┃╭╮┃┣┫┃╭╮┃┃╭╮┃┃╭╮┃┃╭╯
# ┃╰┻━┃┃╰╮┃╭╮┃┃╰╯┃┃┃┃╭╮┃┃╰╯┃┃╰╯┃┃┃╱
# ╰━━━╯╰━╯╰╯╰╯╰━━╯╰╯╰╯╰╯╰━━╯╰━━╯╰╯╱
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱

ComandosPermitidos:
  - 'ping'
  - 'glad sair'
  - 'glad info'

